### ISSUE TITLE
How to publish?

### ISSUE THREAD

**Issue by dotnetshadow** [SoftwareAteliers/asp-net-core-vue-starter#17]
Great template,

I was wondering how you go about publishing the application? 
I tried the following:
`dotnet publish -c Release -o c:\foo`

But when I go to run 
`dotnet  AspNetCoreVueStarter.dll` I get the following error:

```
An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'serve' exited without indicating that the server was listening for requests. The error output was: npm ERR! path


npm ERR! code ENOENT

npm ERR! errno -4058

npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\foo\ClientApp\package.json'

npm ERR! enoent This is related to npm not being able to find a file.

npm ERR! enoent
```

Running node v10.16.3 and npm 6.9.0

**Comment by liborpansky** [comment]
Hi, it looks like you're running in dev environment. The template uses `Microsoft.AspNetCore.Hosting.HostingEnvironmentExtensions` `IsDevelopment()` function to check whether you're running in dev environment. If so, it uses Vue CLI middleware to run `npm run serve` and tries to find the package.json in ClientApp folder.

Ensure that you're running in production environment to skip npm run serve command.

Actually I've never encounter such a problem, because I always publish directly to Windows Server VM (with .net Core Windows hosting bundle) or Azure.

**Comment by dotnetshadow** [comment]
@liborpansky cheers, I was thinking I was encountering some sort of "development" environment
I'll try to disable the code to see if it publishes. But what would the general idea be if I did publish to a directory, then who would be serving up the vue part? (sorry I'm new to vuejs, just trying to get my head around it)

**Comment by liborpansky** [comment]
You can disable it, but you'll be still running in DEV environment (with developer exception handling, no HSTS and HTTPS redirect etc.) It's better to ensure that you're running in PROD instead of disabling code meant to be for dev only...
Vue part will be served by ASP.NET: `app.UseSpaStaticFiles()` in Startup file handles loading of client app from dist folder.
BTW: publish is automatically in Release, it's the environment where you're running .NET app, not how you publish.

**Comment by dotnetshadow** [comment]
Thanks for that. Yep, I was testing to make sure that commenting out would work. 

I did try `dotnet publish -c Release -o c:\foo` but it still thinks it's in development for some reason and I even edited the web.config in the output to set the environment to production . I guess I need to check the environment variable being set

**Comment by dotnetshadow** [comment]
@liborpansky  you were correct, when running the project I had to use 
`dotnet AspNetCoreVueStarter.dll -c Release`

**Comment by liborpansky** [comment]
I've already [migrated](https://github.com/SoftwareAteliers/asp-net-core-vue-starter/tree/16-netcore30) the project to .NET Core 3.0, now I'm waiting for a stable version of Vue CLI Middleware to be released.
I've tested VueCliMiddleware v. 3.0.0-preview7-1 and HMR works as expected, but there are probably some things to test before a production release.
