### ISSUE TITLE
Fetch data does not find endpoint

### ISSUE THREAD

**Issue by stilren** [SoftwareAteliers/asp-net-core-vue-starter#8]
I just cloned this repo and ran dotnet run - fetch data did not work. It could not find the endpoint (resulting in a 404)

local dotnet version is 2.2.204 if it matters

**Comment by stilren** [comment]
adding a vue.config.js file and specifying the devServer works

module.exports = {
  devServer: {
    proxy: "http://localhost:5000"
  }
};

**Comment by liborpansky** [comment]
Hi, thank you for your feedback! I will add some error handling in case fetch fails...
You used client app URL at http://localhost:8080 and set dev proxy to ASP.NET running at port http://localhost:5000. Generally you make it otherwise: requests sending to ASP.NET site at port :5000 using Vue CLI proxy to client app at :8080, but the result is the same...
