### ISSUE TITLE
error MSB1009: Project file does not exist

### ISSUE THREAD

**Issue by raju-tiwari** [SoftwareAteliers/asp-net-core-vue-starter#9]
error MSB1009: Project file does not exist
![Capture](https://user-images.githubusercontent.com/49838285/58503089-7e4be200-81a5-11e9-8df4-fb41eebf6ded.JPG)

**Comment by liborpansky** [comment]
Hi, can you confirm me the .csproj file exists and your current working directory is correct? According to [Microsoft blog](https://social.msdn.microsoft.com/Forums/en-US/7b7808fe-bbca-4ed2-8d41-4f1dcb3b8d4c/msbuild-error-msb1009-project-file-does-not-exist?forum=biztalkgeneral) it can be caused by a missing file or:
> ...if no directory was specified, the project file does not exist in the current working directory

**Comment by liborpansky** [comment]
This issue has been closed because it has been inactive for 30 days. Feel free to reopen this issue if you encounter the same problem.
